version: '3.8'

services:
  # Database service
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=wallet_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-key-for-development-only
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - MONNIFY_API_KEY=${MONNIFY_API_KEY}
      - MONNIFY_SECRET_KEY=${MONNIFY_SECRET_KEY}
      - MONNIFY_CONTRACT_CODE=${MONNIFY_CONTRACT_CODE}
      - MONNIFY_BASE_URL=https://sandbox.monnify.com/api/v1
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # Frontend service
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    command: npm start

volumes:
  postgres_data:
